/**
 * Issued German district codes (Unterscheidungszeichen), including expiring
 * codes still on the road and federal/military codes (X, Y, THW).
 * Source: de.wikipedia.org 'Liste der Kfz-Kennzeichen in Deutschland'
 * (retrieved 2026-07-27, 732 codes). Umlaut codes are stored as
 * written on the plate (TÖL); OCR reads them in ASCII form — resolve through
 * UMLAUT_DISTRICTS before lookup where needed.
 */
const CODES = [
  "A AA AB ABG ABI AC AE AH AIB AIC AK ALF ALZ AM AN ANA",
  "ANG ANK AP APD ARN ART AS ASL ASZ AT AU AUR AW AZ AZE AÖ",
  "B BA BAD BAR BB BBG BBL BC BCH BD BE BED BEL BER BF BGD",
  "BGL BH BI BID BIN BIR BIT BIW BK BKS BL BLB BLK BM BN BNA",
  "BO BOG BOH BOR BOT BP BR BRA BRB BRG BRK BRL BRV BS BSB BSK",
  "BT BTF BUL BW BWL BYL BZ BÖ BÜD BÜR BÜS BÜZ C CA CAS CB",
  "CE CHA CLP CLZ CO COC COE CR CUX CW D DA DAH DAN DAU DBR",
  "DD DE DEG DEL DGF DH DI DIL DIN DIZ DKB DL DLG DM DN DO",
  "DON DS DT DU DUD DW DZ DÜW E EA EB EBE EBN EBS ECK ED",
  "EE EF EG EH EI EIC EIL EIN EIS EL EM EMD EMS EN ER ERB",
  "ERH ERK ERZ ES ESB ESW EU EW F FB FD FDB FDS FEU FF FFB",
  "FG FI FKB FL FLÖ FN FO FOR FR FRG FRI FRW FS FT FTL FW",
  "FZ FÜ FÜS G GA GAN GAP GC GD GDB GE GEL GEO GER GF GG",
  "GHA GHC GI GK GL GLA GM GMN GN GNT GOA GOH GP GR GRA GRH",
  "GRI GRM GRZ GS GT GTH GUB GUN GV GVM GW GZ GÖ GÜ H HA",
  "HAB HAL HAM HAS HB HBN HBS HC HCH HD HDH HDL HE HEB HEF HEI",
  "HEL HER HET HF HG HGN HGW HH HHM HI HIG HIP HK HL HM HMÜ",
  "HN HO HOG HOH HOL HOM HOR HOT HP HR HRO HS HSK HST HU HV",
  "HVL HWI HX HY HZ HÖS IGB IK IL ILL IN IZ J JB JE JL",
  "JÜL K KA KB KC KE KEH KEL KEM KF KG KH KI KIB KK KL",
  "KLE KLZ KM KN KO KR KRU KS KT KU KUS KW KY KYF KÖN KÖT",
  "KÖZ KÜN L LA LAN LAU LB LBS LBZ LC LD LDK LDS LE LEO LER",
  "LEV LF LG LH LI LIB LIF LIP LK LL LM LN LOS LP LR LRO",
  "LSA LSN LSZ LU LUK LUP LWL LÖ LÖB LÜN M MA MAB MAI MAK MAL",
  "MB MC MD ME MED MEG MEI MEK MEL MER MET MG MGH MGN MH MHL",
  "MI MIL MK MKK ML MM MN MO MOD MOL MON MOS MQ MR MS MSE",
  "MSH MSP MST MTK MTL MU MUC MVL MW MY MYK MZ MZG MÜ MÜB MÜL",
  "MÜR N NAB NAI NAU NB ND NDH NE NEA NEB NEC NEN NES NEU NEW",
  "NF NH NI NK NL NM NMB NMS NOH NOL NOM NOR NP NR NRW NT",
  "NU NVP NW NWM NY NZ NÖ OA OAL OB OBB OBG OC OCH OD OE",
  "OF OG OH OHA OHV OHZ OK OL OP OPR OS OSL OTW OVI OVL OZ",
  "P PA PAF PAN PAR PB PCH PE PEG PF PI PIR PL PLÖ PM PN",
  "PR PRÜ PS PW PZ QFT QLB R RA RC RD RDG RE REG REH REI",
  "RG RH RI RID RIE RL RM RN RO ROD ROF ROK ROL ROS ROT ROW",
  "RP RPL RS RSL RT RU RV RW RZ RÜD RÜG S SAB SAD SAL SAN",
  "SAW SB SBG SBK SC SCZ SDH SDL SDT SE SEB SEE SEF SEL SFB SFT",
  "SG SGH SH SHA SHG SHK SHL SI SIG SIM SK SL SLE SLF SLG SLK",
  "SLN SLS SLZ SLÜ SM SMÜ SN SO SOB SOG SOK SON SP SPB SPN SR",
  "SRB SRO ST STA STB STD STE STL STO SU SUL SW SWA SY SZ SZB",
  "SÄK SÖM SÜW TBB TDO TE TET TF TG THL THW TIR TO TP TR TS",
  "TT TUT TÖL TÜ UE UEM UFF UH UL UM UN USI V VAI VB VEC",
  "VER VG VIB VIE VIT VK VOH VR VS W WA WAF WAK WAN WAR WAT",
  "WB WBS WDA WE WEL WEN WER WES WF WG WHV WI WIL WIS WIT WIZ",
  "WK WL WLG WM WMS WN WND WO WOB WOH WOL WOR WOS WR WRN WS",
  "WSF WST WSW WT WTL WTM WUG WUN WUR WW WZ WZL WÜ WÜM X Y",
  "Z ZE ZEL ZI ZIG ZP ZR ZS ZW ZZ ÖHR ÜB",
].join(' ')

export const ISSUED_DISTRICTS: ReadonlySet<string> = new Set(CODES.split(' '))
